# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
  #     desired widget in your `content/home/` folder.
  #   The weight parameter defines the order that the links will appear in.

main:
  - name: Home
    url: /
    weight: 10
  - name: Research Areas
    url: /research-areas
    weight: 20
  - name: Projects
    url: /projects
    weight: 30
  - name: Activities
    url: /activities
    weight: 40

