# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
  #     desired widget in your `content/home/` folder.
  #   The weight parameter defines the order that the links will appear in.

main:
  - name: Home
    url: /
    weight: 10
  - name: About Me
    url: /about-me
    weight: 15
  - name: Research Areas
    url: /research-areas
    weight: 20
  - name: Projects
    identifier: projects
    weight: 30
  - name: Project Summary
    url: /project-summary
    weight: 40
  - name: Activities
    url: /activities
    weight: 50

  - name: FGO Positioning
    parent: projects
    url: /projects/fgo-positioning
    weight: 31

  - name: UAV Path Planning
    parent: projects
    url: /projects/path-planning
    weight: 32

  - name: UAV Vision Landing
    parent: projects
    url: /projects/vision-landing
    weight: 33

  - name: Ionosphere Modeling
    parent: projects
    url: /projects/iono-modeling
    weight: 34

  - name: LEO PNT
    parent: projects
    url: /projects/leo-pnt
    weight: 35
  
  - name: SDR
    parent: projects
    url: /projects/sdr
    weight: 36